server:
  port: 8008
  jackson:
    property-naming-strategy: SNAKE_CASE

spring:
  datasource:
    url: jdbc:mysql://moram:morammoram12@moram-moram.cwjdlhpngx8e.us-east-2.rds.amazonaws.com:3306/moram_moram
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  jpa:
    show-sql: true
auth:
  jwt:
    secret: 45VCO4fzXw4O32IV0qF3hixZLWChc4WiB9li3mw-WPcnfe7c
    exp:
      access: ${JWT_ACCESS_EXP:3600}
      refresh: ${JWT_REFRESH_EXP:3600}
    header:
      access: ${JWT_HEADER:Authorization}
      refresh: ${JWT_REFRESH_HEADER:Refresh-Token}
    prefix: ${JWT_PREFIX:Bearer}

post:
  image:
    path: ${IMAGE_PATH:/}