server:
  port: 8088
  jackson:
    property-naming-strategy: SNAKE_CASE

spring:
  datasource:
    url: ${DATABASE_URL:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

posts:
  image:
    path: ${IMAGE_PATH:/}

image:
  upload:
    dir: /

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

auth:
  jwt:
    secret: ${JWT_SECRET:}
    exp:
      access: ${JWT_ACCESS_EXP:3600}
      refresh: ${JWT_REFRESH_EXP:3600}
    header:
      access: ${JWT_HEADER:Authorization}
      refresh: ${JWT_REFRESH_HEADER:Refresh-Token}
    prefix: ${JWT_PREFIX:Bearer}

post:
  file:
    path: ${IMAGE_PATH:/}
