server:
  port: 8008
  jackson:
    property-naming-strategy: SNAKE_CASE
  servlet:
    encoding:
      charset: UTF-8
      force: true
      force-response: true
      force-request: true

spring:
  datasource:
    url: ${MYSQL_URL:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ${REDIS_HOST:}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PW:}
  jpa:
    show-sql: true

auth:
  jwt:
    secret: ${JWT_SECRET_KEY:}
    exp:
      access: ${JWT_ACCESS_EXP:3600}
      refresh: ${JWT_REFRESH_EXP:3600}
    header:
      access: ${JWT_HEADER:Authorization}
      refresh: ${JWT_REFRESH_HEADER:Refresh-Token}
    prefix: ${JWT_PREFIX:Bearer}

post:
  image:
    path: ${IMAGE_PATH:/}