name: Spring Boot & Gradle CI/CD 

on:
  push:
    branches: 
    - main
    - develop
  pull_request:
    branches: [ main, develop ]

jobs:
  CI:
    runs-on: ubuntu-latest
    env: 
        MYSQL_URL: ${{secrets.MYSQL_URL}}
        JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        DOCKER_USERNAME: ${{secrets.USERNAME}}
        REDIS_HOST: ${{secrets.REDIS_HOST}}
        REDIS_PW: ${{secrets.REDIS_PW}}
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew clean build
      
  CD:
    runs-on: ubuntu-latest
    needs: CI
    env: 
        MYSQL_URL: ${{secrets.MYSQL_URL}}
        JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        DOCKER_USERNAME: ${{secrets.USERNAME}}
        REDIS_HOST: ${{secrets.REDIS_HOST}}
        REDIS_PW: ${{secrets.REDIS_PW}}
        
      
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
      
    - name: grant privileges to gradlew
      run: chmod +x gradlew

    - name: run build
      run: ./gradlew clean build
      
    - name: Build Docker Image
      run: docker build --tag birthfit .

    - name: Upload to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: joungeun/morammoram
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 
